namespace: dev
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
- ../../../../base/securebanking

patchesStrategicMerge:
  - configmap.yaml

images:
- name: ig
  newName: eu.gcr.io/sbat-gcr-develop/securebanking/gate/ig
  newTag: latest
