apiVersion: v1
kind: ConfigMap
metadata:
  name: securebanking-platform-config
data:
  BASE_FQDN: mariantiris.forgerock.financial
  IG_FQDN: obdemo.mariantiris.forgerock.financial
  RS_FQDN: rs.mariantiris.forgerock.financial
  RCS_FQDN: rcs.mariantiris.forgerock.financial
  RCS_UI_FQDN: rcs-ui.mariantiris.forgerock.financial
  IDENTITY_PLATFORM_FQDN: iam.mariantiris.forgerock.financial