apiVersion: v1
kind: ConfigMap
metadata:
  name: securebanking-platform-config
data:
  BASE_FQDN: dev.forgerock.financial
  IG_FQDN: obdemo.dev.forgerock.financial
  RS_FQDN: rs.dev.forgerock.financial
  RCS_FQDN: rcs.dev.forgerock.financial
  RCS_UI_FQDN: rcs-ui.dev.forgerock.financial
  IDENTITY_PLATFORM_FQDN: iam.dev.forgerock.financial