namespace: dev
commonLabels:
  app.kubernetes.io/name: "forgerock"
resources:
- ../defaults

patchesJson6902:
  - path: secrets-prometheus-patch.yaml
    target:
      kind: Secret
      name: openig-secrets-env
      version: v1
