apiVersion: v1
kind: ConfigMap
metadata:
  name: securebanking-platform-config
data:
  BASE_FQDN: christian-brindley.forgerock.financial
  IG_FQDN: obdemo.christian-brindley.forgerock.financial
  RS_FQDN: rs.christian-brindley.forgerock.financial
  RCS_FQDN: rcs.christian-brindley.forgerock.financial
  RCS_UI_FQDN: rcs-ui.christian-brindley.forgerock.financial
  IDENTITY_PLATFORM_FQDN: iam.christian-brindley.forgerock.financial
